name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0
      - name: Install pnpm 
        uses: pnpm/action-setup@v2
       
      - name: Setup Node.js v16
        uses: actions/setup-node@v2
        with:
          # 选择要使用的 node 版本
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install --no-frozen-lockfile

      # 运行构建脚本
      - name: Build VuePress site
        run: pnpm run build:docs

      - name: publish
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: packages/vuepress-v2/docs/.vuepress/dist/
          destination-github-username: 'flybbjcs70'
          destination-repository-name: 'flybbjcs70.github.io'
          user-email: wenze@126.com
          commit-message: vuepress-v2 publish from $GITHUB_REF
          target-branch: master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}     

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      # - name: Deploy to GitHub Pages
      #   uses: crazy-max/ghaction-github-pages@v2
      #   with:
      #     # 部署到 gh-pages 分支
      #     target_branch: master
      #     repo: flybbjcs70/flybbjcs70.github.io
      #     # 部署目录为 VuePress 的默认输出目录
      #     build_dir: packages/vuepress-v2/docs/.vuepress/dist
      #   env:
      #     # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
